apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: labelled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: markmorcos/labelled-auth
          envFrom:
            - configMapRef:
                name: global-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SENDGRID_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid-secret
                  key: SENDGRID_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: labelled
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
---

