apiVersion: apps/v1
kind: Deployment
metadata:
  name: queries-redis-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queries-redis
  template:
    metadata:
      labels:
        app: queries-redis
    spec:
      containers:
        - name: queries-redis
          image: redis
          volumeMounts:
            - name: queries-redis-storage
              mountPath: /data
      volumes:
        - name: queries-redis-storage
          persistentVolumeClaim:
            claimName: queries-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: queries-redis-srv
spec:
  selector:
    app: queries-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
