apiVersion: apps/v1
kind: Deployment
metadata:
  name: queries-depl
  namespace: labelled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queries
  template:
    metadata:
      labels:
        app: queries
    spec:
      containers:
        - name: queries
          image: markmorcos/labelled-queries
          envFrom:
            - configMapRef:
                name: global-config
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SHOPIFY_KEY
              valueFrom:
                secretKeyRef:
                  name: shopify-secret
                  key: SHOPIFY_KEY
            - name: SHOPIFY_STORE
              value: "5c1dc6-2.myshopify.com"
            - name: REDIS_HOST
              value: queries-redis-srv
---
apiVersion: v1
kind: Service
metadata:
  name: queries-srv
  namespace: labelled
spec:
  selector:
    app: queries
  ports:
    - name: queries
      protocol: TCP
      port: 3000
      targetPort: 3000
