apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl
  namespace: labelled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: markmorcos/labelled-web
          envFrom:
            - configMapRef:
                name: global-config
---
apiVersion: v1
kind: Service
metadata:
  name: web-srv
  namespace: labelled
spec:
  selector:
    app: web
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
