name: manifest

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Loop and apply YAMLs over SSH stdin
        run: |
          echo "${{ secrets.RASPBERRY_PI_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

          cat infra/production/*.yaml infra/*.yaml | ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no \
          "${{ secrets.RASPBERRY_PI_USERNAME }}@${{ secrets.RASPBERRY_PI_HOST }}" \
          "export KUBECONFIG=/home/mark/.kube/config && kubectl apply -f -"
