name: queries

on:
  workflow_dispatch: {}
  push:
    paths:
      - "queries/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd queries && npm install && npm run build

  deploy:
    runs-on: ubuntu-24.04-arm
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          cd queries
          docker build . -f Dockerfile.production -t markmorcos/labelled-queries
          docker push markmorcos/labelled-queries
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.RASPBERRY_PI_HOST }}
          username: ${{ secrets.RASPBERRY_PI_USERNAME }}
          key: ${{ secrets.RASPBERRY_PI_SSH_KEY }}
          script: |
            export KUBECONFIG=/home/mark/.kube/config
            kubectl rollout restart deployment queries-depl -n labelled
